#!/bin/bash
#SBATCH -A IscrC_XAI-MRAG
#SBATCH -p boost_usr_prod
#SBATCH --time=0-23:00:00
#SBATCH --mem=32000
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -c 8
#SBATCH --gres=gpu:1
#SBATCH --output=sbatch_files/output/evaluate_answers_llama3_8B_abliterated.out
#SBATCH --job-name evaluate_answers_llama3_8B_abliterated
#SBATCH --dependency=afterok:13463159

model_data_id="mlabonne/Meta-Llama-3.1-8B-Instruct-abliterated"
batch_size=8 # Reduce batch size to avoid OOM errors.
seed=10

source ../../ups_gen_env/bin/activate
source ../../populate_env_vars.sh

echo "Evaluating answers generated by model: $model_data_id"

python wright_open_to_close.py --model_data_id $model_data_id --batch_size $batch_size --seed $seed